# Generated by Django 4.1.6 on 2023-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='product_cate_name',
            field=models.CharField(max_length=100),
        ),
    ]
