# Generated by Django 4.1.6 on 2023-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_brands_alter_products_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_brand',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='brands',
        ),
    ]
