# Generated by Django 4.1.6 on 2023-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_products_product_brand_delete_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_brand',
            field=models.CharField(max_length=20),
        ),
    ]
