# Generated by Django 4.1.6 on 2023-03-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brand'),
        ),
    ]
