# Generated by Django 4.1.6 on 2023-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_products_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img1',
            field=models.ImageField(default='', upload_to='Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img2',
            field=models.ImageField(default='', upload_to='Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img3',
            field=models.ImageField(default='', upload_to='Image'),
        ),
    ]
