# Generated by Django 4.1.6 on 2023-03-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_products_product_img1_products_product_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_img1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_img2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_img3',
        ),
    ]
