# Generated by Django 4.1.6 on 2023-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='shade',
            field=models.CharField(default='shade', max_length=20),
        ),
    ]
