# Generated by Django 4.1.6 on 2023-03-18 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mycart_shade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=1000)),
                ('details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
