# Generated by Django 4.1.6 on 2023-03-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileupload',
        ),
    ]
