# Generated by Django 4.1.6 on 2023-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='shades',
            field=models.CharField(default='No shade', max_length=100),
        ),
    ]
